function Sujeto = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SUJETO = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  SUJETO1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Sujeto1 = importfile("C:\Users\Soporte\OneDrive - Universidad Autonoma de Guadalajara\Documentos\MATLAB\Comparacion_EMG\Datos\Sujeto_1.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Dec-2022 16:33:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Sujeto = readtable(filename, opts);

%% Convert to output type
Sujeto = table2array(Sujeto);
end